try to deploy to ec2

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -112,13 +112,35 @@ jobs:
           
             sudo systemctl restart docker
           
-            aws ecr get-login-password --region ap-northeast-1 | docker login \
-                --username AWS \
-                --password-stdin ${{ steps.get-ecr-repo.outputs.repository_uri }}
+            if ! command -v aws &> /dev/null; then
+              sudo apt update
+              sudo apt install -y unzip
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+              aws --version
+            fi
+            
+            REPO_URI="${{ steps.get-ecr-repo.outputs.repository_uri }}"
+            echo "Trying to login ECR: $REPO_URI"
+            LOGIN_RESULT=$(echo "$(aws ecr get-login-password --region ap-northeast-1)" | \
+            docker login -u AWS --password-stdin $REPO_URI 2>&1)
+            echo "$LOGIN_RESULT"
+            echo "$LOGIN_RESULT" | grep -q "Login Succeeded" || { echo "::error::ECR login failed"; exit 1; }
+            
+            if docker ps -a | grep -q myapp-container; then
+              echo "stopping old container..."
+              timeout 30 docker stop myapp-container || true
+              docker rm myapp-container || true
+              else
+              echo "no any running container myapp-container"
+            fi
           
             timeout 30 docker stop myapp-container || true
             docker rm myapp-container || true
           
+            IMAGE_TAG="$REPO_URI:${{ github.sha }}"
+            echo "start new container : $IMAGE_TAG"
             docker run -d \
               --name myapp-container \
               -e SPRING_DATASOURCE_URL=jdbc:postgresql://${{ steps.rds.outputs.DB_ENDPOINT }}/emsp-db \
@@ -128,13 +150,13 @@ jobs:
               --health-cmd="curl -f http://localhost:8080/health || exit 1" \
               --health-interval=5s \
               --health-retries=3 \
-              ${{ steps.get-ecr-repo.outputs.repository_uri }}:${{ github.sha }}
+              $IMAGE_TAG
           
               sleep 10
               CONTAINER_STATUS=$(docker inspect -f '{{.State.Status}}' myapp-container)
               if [ "$CONTAINER_STATUS" != "running" ]; then
-              echo "::error::Container failed to start!"
-              docker logs myapp-container
-              exit 1
+                echo "::error::Container failed to start!"
+                docker logs myapp-container
+                exit 1
               fi
           ENDSSH
