try to fix jar can not find problem.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,7 +44,7 @@ jobs:
         run: |
           echo "Generated JAR files:"
           ls -l target/*.jar
-          [ -f target/app.jar ] || (echo "JAR not found!"; exit 1)
+          [ -f target/assignment-0.0.1-SNAPSHOT.jar ] || (echo "JAR not found!"; exit 1)
 
       # 显示JAR文件路径信息
       - name: Debug JAR location
